### ISSUE TITLE
move to @ariatype namespace

### ISSUE THREAD

**Issue by durksteedjr** [ocavue/aria-ui#156]
Hi, maintainer of [ariatype](https://github.com/ariatype) here. The project was previously under the `@dddstack` namespace; however, now will be under `@ariatype` going forward.

`@dddstack` namespace packages will be deprecated and any future updates will be on the `@ariatype` namespace packages. All types and imports will remain the same, feel free to [look at the documentation](https://github.com/ariatype/ariatype/blob/main/@ariatype/ariatype/README.md).

Very cool project!

**Comment by ocavue** [comment]
Thanks for building `@dddstack` and `@ariatype`.
